//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanizeDotNet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HumanizeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HumanizeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HumanizeDotNet.Resources.HumanizeResources", typeof(HumanizeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute ago.
        /// </summary>
        public static string a_minute_ago {
            get {
                return ResourceManager.GetString("a_minute_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute from now.
        /// </summary>
        public static string a_minute_from_now {
            get {
                return ResourceManager.GetString("a_minute_from_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a second ago.
        /// </summary>
        public static string a_second_ago {
            get {
                return ResourceManager.GetString("a_second_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a second from now.
        /// </summary>
        public static string a_second_from_now {
            get {
                return ResourceManager.GetString("a_second_from_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        public static string an_hour_ago {
            get {
                return ResourceManager.GetString("an_hour_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour from now.
        /// </summary>
        public static string an_hour_from_now {
            get {
                return ResourceManager.GetString("an_hour_from_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to billion.
        /// </summary>
        public static string billion {
            get {
                return ResourceManager.GetString("billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decillion.
        /// </summary>
        public static string decillion {
            get {
                return ResourceManager.GetString("decillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eight.
        /// </summary>
        public static string eight {
            get {
                return ResourceManager.GetString("eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to five.
        /// </summary>
        public static string five {
            get {
                return ResourceManager.GetString("five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to four.
        /// </summary>
        public static string four {
            get {
                return ResourceManager.GetString("four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to googol.
        /// </summary>
        public static string googol {
            get {
                return ResourceManager.GetString("googol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to million.
        /// </summary>
        public static string million {
            get {
                return ResourceManager.GetString("million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string n_days_ago {
            get {
                return ResourceManager.GetString("n_days_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days from now.
        /// </summary>
        public static string n_days_from_now {
            get {
                return ResourceManager.GetString("n_days_from_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string n_hours_ago {
            get {
                return ResourceManager.GetString("n_hours_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours from now.
        /// </summary>
        public static string n_hours_from_now {
            get {
                return ResourceManager.GetString("n_hours_from_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string n_minutes_ago {
            get {
                return ResourceManager.GetString("n_minutes_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes from now.
        /// </summary>
        public static string n_minutes_from_now {
            get {
                return ResourceManager.GetString("n_minutes_from_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        public static string n_seconds_ago {
            get {
                return ResourceManager.GetString("n_seconds_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds from now.
        /// </summary>
        public static string n_seconds_from_now {
            get {
                return ResourceManager.GetString("n_seconds_from_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nd.
        /// </summary>
        public static string nd {
            get {
                return ResourceManager.GetString("nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nine.
        /// </summary>
        public static string nine {
            get {
                return ResourceManager.GetString("nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonillion.
        /// </summary>
        public static string nonillion {
            get {
                return ResourceManager.GetString("nonillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string now {
            get {
                return ResourceManager.GetString("now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to octillion.
        /// </summary>
        public static string octillion {
            get {
                return ResourceManager.GetString("octillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one.
        /// </summary>
        public static string one {
            get {
                return ResourceManager.GetString("one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day ago.
        /// </summary>
        public static string one_day_ago {
            get {
                return ResourceManager.GetString("one_day_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day from now.
        /// </summary>
        public static string one_day_from_now {
            get {
                return ResourceManager.GetString("one_day_from_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quadrillion.
        /// </summary>
        public static string quadrillion {
            get {
                return ResourceManager.GetString("quadrillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quintillion.
        /// </summary>
        public static string quintillion {
            get {
                return ResourceManager.GetString("quintillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rd.
        /// </summary>
        public static string rd {
            get {
                return ResourceManager.GetString("rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to septillion.
        /// </summary>
        public static string septillion {
            get {
                return ResourceManager.GetString("septillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seven.
        /// </summary>
        public static string seven {
            get {
                return ResourceManager.GetString("seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sextillion.
        /// </summary>
        public static string sextillion {
            get {
                return ResourceManager.GetString("sextillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to six.
        /// </summary>
        public static string six {
            get {
                return ResourceManager.GetString("six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st.
        /// </summary>
        public static string st {
            get {
                return ResourceManager.GetString("st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th.
        /// </summary>
        public static string th {
            get {
                return ResourceManager.GetString("th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three.
        /// </summary>
        public static string three {
            get {
                return ResourceManager.GetString("three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string tomorrow {
            get {
                return ResourceManager.GetString("tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trillion.
        /// </summary>
        public static string trillion {
            get {
                return ResourceManager.GetString("trillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two.
        /// </summary>
        public static string two {
            get {
                return ResourceManager.GetString("two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string yesterday {
            get {
                return ResourceManager.GetString("yesterday", resourceCulture);
            }
        }
    }
}
